### ISSUE TITLE
Diffie Hellman

### ISSUE THREAD

**Issue by arik-so** [BitcoinPHP/BitcoinECDSA.php#31]
Hi! It would be super useful if you implemented a method to support Diffie Hellman. That is, given one keypair's public key and another keypair's private key, multiplying the two yields a very useful symmetric key.

**Comment by rgex** [comment]
Hi arik, this can be easily done using the mulPoint method.
$bitcoinECDSA->mulPoint($k, $point);
$k is your private key as a GMP ressource, and $point an array with the format 
['x'=>(GMP ressource), 'y' => (GMP ressource)]

If you give me an ECDH encoding standard (may be DER) I can add a method that render it that way.

**Comment by arik-so** [comment]
Thanks, I found the mulPoint method and implemented Diffie Hellman. I'm applying a sha256 to the result (which is the new point in DER format) to restrict the output to 32 bytes so it can be used as an AES-256 key.
