### ISSUE TITLE
different results 

### ISSUE THREAD

**Issue by hgisoeura** [BitcoinPHP/BitcoinECDSA.php#35]
Hi,

I'm getting different results with getAddress() when using compressed and uncompressed private keys.

compressed bitcoin address: 155NQk5psqEsDjfbYV5iWhGpVhm3GeLYBs
$key uncompressed: 5Hpepo99cdVV4xhMFUYteoHzW7M5hdccMmMpniKa11wNsUhxqfi
$key compressed: KwFKwxey2G4itUq6NtbkyqKzoV1dkLcB4enuvmNxf591XjhLzdCe

$bitcoinECDSA->setPrivateKeyWithWif($key);
$address = $bitcoinECDSA->getAddress();
echo $address;

Result for uncompressed key:
155NQk5psqEsDjfbYV5iWhGpVhm3GeLYBs (correct)

Result for compressed key:
1PShnSX6kerVFkC8MhuLwL1uhxL2aCBsJt (wrong)

**Comment by rgex** [comment]
The public key is compressed not the private key.
For one private key you can have one compressed public key 33bytes and one uncompressed 65bytes. As the address is the hash of the public key it means that for one private key you can get two different addresses the compressed on and the uncompressed one.
Take a look here: https://bitcoin.stackexchange.com/a/3062/10621

**Comment by rgex** [comment]
The answer bellow explains it even better https://bitcoin.stackexchange.com/a/3839/10621

**Comment by rgex** [comment]
I think I got what you mean. i'll take a look at it

**Comment by rgex** [comment]
I pushed some changes to the master. Now there is a getWif method for getting the compressed WIF and getUncompressedWif method for getting the uncompressed wif.
It will actually export the same private key but there will be a little flag to tell the Bitcoin Client what kind of address it should generate from it.

**Comment by rgex** [comment]
Fix released in v 1.3.3
