### ISSUE TITLE
Undefined function 'BitcoinPHP\BitcoinECDSA\getWif'.

### ISSUE THREAD

**Issue by tzak902** [BitcoinPHP/BitcoinECDSA.php#42]
hi,
line code 912 shows getwif as undefined function

public function getUncompressedWif()
    {
        return getWif(false);
    }

**Comment by rgex** [comment]
Defined here: https://github.com/BitcoinPHP/BitcoinECDSA.php/blob/5bac52ec7f27b528da349f4087dd6bd37637d17c/src/BitcoinPHP/BitcoinECDSA/BitcoinECDSA.php#L883

**Comment by rgex** [comment]
It was fixed in the latest release
